"""Every figure in the report, drawn from the artifact store and nothing else.

Build spec 20: every figure and table is a file generated by the pipeline. This script is
the generator for the figures. It reads the ingest, grid, and audit stage artifacts for the
current config hash and writes vector PDFs into ``report/figures/``.

It reads no CSV from outside the repository and computes no headline statistic that a stage
has not already recorded. Where a figure needs a derived quantity for its own annotation (a
Pearson correlation on a scatter, a pointwise percentile band), it computes it from the
artifact it is plotting and writes it to ``figure_stats.json`` beside this file, so even the
annotations are traceable.

Style comes from :mod:`ufem.plotting.style`, the single style module of build spec section 8.
The two figures the audit phase adds, the completion probability surface and the calibration
reliability diagram, are drawn by :mod:`ufem.plotting.censoring`.

Deterministic: no random number generation anywhere, and the PDF creation timestamp is pinned
by the style module, so rerunning on unchanged artifacts reproduces the bytes.

Run it from the repository root after `ufem run all`:

    .venv/Scripts/python report/figures_src/make_figures.py
"""

from __future__ import annotations

import json
import pickle
import sys
from pathlib import Path

import numpy as np
import pandas as pd

REPO_ROOT = Path(__file__).resolve().parents[2]
if str(REPO_ROOT / "src") not in sys.path:
    sys.path.insert(0, str(REPO_ROOT / "src"))

from matplotlib import pyplot as plt  # noqa: E402
from matplotlib.lines import Line2D  # noqa: E402
from matplotlib.patches import Patch  # noqa: E402

from ufem.audit import (  # noqa: E402
    COMPLETION_JSON,
    COMPLETION_PICKLE,
    STATUS_VALID,
    VALIDITY_DOMAIN_JSON,
    VALIDITY_PARQUET,
)
from ufem.audit import STAGE_NAME as AUDIT_STAGE  # noqa: E402
from ufem.config import FEATURE_ORDER, config_hash, features, load_config  # noqa: E402
from ufem.grid import (  # noqa: E402
    DAMAGE_GRID_PARQUET,
    QOI_PARQUET,
    RF2_GRID_PARQUET,
    displacement_grid,
    raw_curve_qoi,
)
from ufem.grid import STAGE_NAME as GRID_STAGE  # noqa: E402
from ufem.ingest import DESIGN_PARQUET, LOAD_PARQUET  # noqa: E402
from ufem.ingest import STAGE_NAME as INGEST_STAGE  # noqa: E402
from ufem.manifest import stage_dir  # noqa: E402
from ufem.plotting.censoring import calibration_plot, completion_surface  # noqa: E402
from ufem.plotting.registration import (  # noqa: E402
    amplitude_loadings,
    registration_before_after,
    scree,
    warp_family,
)
from ufem.plotting.style import (  # noqa: E402
    C_BAND,
    C_INK_2,
    C_MUTED,
    C_SERIES_1,
    C_SERIES_2,
    FIG_WIDTH_IN,
    annotation_style,
    apply_style,
    save_figure,
)
from ufem.plotting.surrogate import predicted_vs_actual  # noqa: E402
from ufem.reduce import BASIS_JSON, fit_basis  # noqa: E402
from ufem.reduce import STAGE_NAME as REDUCE_STAGE  # noqa: E402
from ufem.register import (  # noqa: E402
    AMPLITUDE_PARQUET,
    AMPLITUDE_UNREGISTERED_PARQUET,
    WARP_PARQUET,
    curve_matrix,
)
from ufem.register import STAGE_NAME as REGISTER_STAGE  # noqa: E402
from ufem.validate import BASELINES_JSON, SCALAR_PREDICTIONS_PARQUET  # noqa: E402
from ufem.validate import STAGE_NAME as VALIDATE_STAGE  # noqa: E402

OUT = REPO_ROOT / "report" / "figures"
ANNOT = annotation_style()
RESULTS: dict = {}


def _stage(name: str, digest: str) -> Path:
    config = load_config(REPO_ROOT)
    directory = stage_dir(REPO_ROOT / config.pipeline.paths.artifact_root, name, digest)
    if not (directory / "manifest.json").is_file():
        raise FileNotFoundError(
            f"the {name} stage has no artifacts at {directory}. Run `ufem run all` before "
            "generating figures: this script plots artifacts and never recomputes them."
        )
    return directory


def pearson(x, y) -> float:
    return float(np.corrcoef(np.asarray(x, float), np.asarray(y, float))[0, 1])


def spearman(x, y) -> float:
    return pearson(pd.Series(x).rank().to_numpy(), pd.Series(y).rank().to_numpy())


def band(matrix: np.ndarray):
    """Pointwise 5th, 50th and 95th percentile across realizations."""
    return np.percentile(matrix, [5, 50, 95], axis=0)


def family_panel(ax, x, matrix, lo, med, hi, lab_lo, lab_hi):
    for row in matrix:
        ax.plot(x, row, color=C_MUTED, lw=0.35, alpha=0.16, solid_capstyle="round", zorder=1)
    ax.fill_between(x, lo, hi, color=C_BAND, alpha=0.55, lw=0, zorder=2)
    ax.plot(x, med, color=C_SERIES_1, lw=1.8, solid_capstyle="round", zorder=3)
    return [
        Line2D([], [], color=C_MUTED, lw=0.9, alpha=0.55,
               label=f"individual runs (n = {matrix.shape[0]})"),
        Patch(facecolor=C_BAND, alpha=0.55, edgecolor="none",
              label=f"pointwise {lab_lo} to {lab_hi} envelope"),
        Line2D([], [], color=C_SERIES_1, lw=1.8, label="pointwise median"),
    ]


def main() -> int:
    apply_style()
    OUT.mkdir(parents=True, exist_ok=True)
    config = load_config(REPO_ROOT)
    digest = config_hash(config)
    ingest_dir = _stage(INGEST_STAGE, digest)
    grid_dir = _stage(GRID_STAGE, digest)
    audit_dir = _stage(AUDIT_STAGE, digest)

    print("Loading artifacts ...")
    design = pd.read_parquet(ingest_dir / DESIGN_PARQUET)
    validity = pd.read_parquet(audit_dir / VALIDITY_PARQUET)
    qoi = pd.read_parquet(grid_dir / QOI_PARQUET)
    rf2_frame = pd.read_parquet(grid_dir / RF2_GRID_PARQUET)
    damage_frame = pd.read_parquet(grid_dir / DAMAGE_GRID_PARQUET)
    completion = json.loads((audit_dir / COMPLETION_JSON).read_text(encoding="utf-8"))
    domain = json.loads((audit_dir / VALIDITY_DOMAIN_JSON).read_text(encoding="utf-8"))
    model = pickle.loads((audit_dir / COMPLETION_PICKLE).read_bytes())

    u_grid = displacement_grid(config)
    value_columns = [name for name in rf2_frame.columns if name != "job"]
    rf2_grid = rf2_frame[value_columns].to_numpy(dtype=float) / 1000.0
    damage_grid = damage_frame[value_columns].to_numpy(dtype=float)

    completed = (validity["status"] == STATUS_VALID).to_numpy(dtype=bool)
    ok = validity.loc[completed]
    bad = validity.loc[~completed]

    RESULTS["n_design"] = int(len(validity))
    RESULTS["n_completed"] = int(completed.sum())
    RESULTS["n_failed"] = int((~completed).sum())
    RESULTS["overall_failure_rate"] = float((~completed).mean())
    print(
        f"  {len(validity)} design points | {completed.sum()} completed | "
        f"{(~completed).sum()} failed | {rf2_grid.shape[0]} curves"
    )

    # The audit's headline peak, displacement at peak and stiffness were measured on the
    # solver's raw adaptive increments, not on the 201 point grid. The report quotes that
    # basis, so the histograms and scatters here use it too, via the pipeline's own
    # implementation of that measurement. See docs/DESIGN_DECISIONS.md.
    load = pd.read_parquet(ingest_dir / LOAD_PARQUET)
    raw = raw_curve_qoi(load)
    raw["sample_id"] = raw["job"].str.rsplit("_", n=1).str[-1].astype("int64")
    raw = raw.merge(design[["sample_id", *FEATURE_ORDER]], on="sample_id", how="left")
    raw = raw.sort_values("sample_id", kind="mergesort").reset_index(drop=True)

    # ------------------------------------------------------------------
    print("fig_ld_family.pdf")
    lo, med, hi = band(rf2_grid)
    fig, ax = plt.subplots(figsize=(FIG_WIDTH_IN, 3.5))
    handles = family_panel(ax, u_grid, rf2_grid, lo, med, hi, "5%", "95%")
    ax.set_xlabel("Mid-span displacement $U_2$ [mm]")
    ax.set_ylabel("Reaction force $RF_2$ [kN]")
    ax.set_xlim(0, u_grid.max())
    ax.set_ylim(0, None)
    ax.legend(handles=handles, loc="lower right")
    save_figure(fig, OUT / "fig_ld_family.pdf")

    peak_index = int(np.argmax(med))
    RESULTS["ld_median_peak_kN"] = float(med.max())
    RESULTS["ld_median_peak_U2_mm"] = float(u_grid[peak_index])
    RESULTS["ld_envelope_width_max_kN"] = float(np.max(hi - lo))
    RESULTS["ld_envelope_width_max_at_U2_mm"] = float(u_grid[int(np.argmax(hi - lo))])
    RESULTS["ld_median_at_U2_20mm_kN"] = float(med[-1])

    # ------------------------------------------------------------------
    print("fig_damage_family.pdf")
    saturation = float(damage_grid.max())
    dlo, dmed, dhi = band(damage_grid)
    fig, ax = plt.subplots(figsize=(FIG_WIDTH_IN, 3.5))
    handles = family_panel(ax, u_grid, damage_grid, dlo, dmed, dhi, "5%", "95%")
    ax.axhline(saturation, color=C_INK_2, lw=0.9, ls=(0, (4, 2.5)), zorder=4)
    ax.annotate(
        f"saturation $d_c = {saturation:.3f}$",
        xy=(0.985, saturation), xycoords=("axes fraction", "data"),
        xytext=(0, -4), textcoords="offset points",
        ha="right", va="top", fontsize=9.0, color=C_INK_2,
    )
    ax.set_xlabel("Mid-span displacement $U_2$ [mm]")
    ax.set_ylabel("Max. compressive damage $d_{c,\\max}$ [-]")
    ax.set_xlim(0, u_grid.max())
    ax.set_ylim(0, 1.02)
    ax.legend(handles=handles, loc="lower right")
    save_figure(fig, OUT / "fig_damage_family.pdf")

    RESULTS["damage_saturation_level"] = saturation
    RESULTS["damage_median_at_U2_10mm"] = float(np.interp(10.0, u_grid, dmed))
    RESULTS["damage_U2_at_half_sat_median_mm"] = float(qoi["u_damage_half_sat_mm"].median())

    # ------------------------------------------------------------------
    print("fig_design_censoring.pdf")
    labels = [
        ("Fcm_MPa", "$f_{cm}$ [MPa]"),
        ("c_nom_bottom_mm", "$c_{nom,bot}$ [mm]"),
        ("c_nom_top_mm", "$c_{nom,top}$ [mm]"),
    ]
    n = len(labels)
    fig, axes = plt.subplots(n, n, figsize=(FIG_WIDTH_IN, FIG_WIDTH_IN * 0.92), sharex="col")
    for i in range(n):
        for j in range(n):
            ax = axes[i, j]
            xk, xl = labels[j]
            yk, yl = labels[i]
            if i == j:
                bins = np.histogram_bin_edges(validity[xk], bins=18)
                ax.hist(ok[xk], bins=bins, color=C_SERIES_1, alpha=0.75, lw=0, zorder=2)
                ax.hist(bad[xk], bins=bins, histtype="step", color=C_SERIES_2, lw=1.1, zorder=3)
                ax.set_yticks([])
                ax.spines["left"].set_visible(False)
                ax.grid(False)
            elif i > j:
                ax.scatter(bad[xk], bad[yk], s=7, facecolor="none", edgecolor=C_SERIES_2,
                           linewidth=0.55, alpha=0.85, zorder=2)
                ax.scatter(ok[xk], ok[yk], s=7, color=C_SERIES_1, lw=0, alpha=0.85, zorder=3)
            else:
                ax.axis("off")
                continue
            if i == n - 1:
                ax.set_xlabel(xl)
            if j == 0 and i > 0:
                ax.set_ylabel(yl)
    axes[0, 0].set_ylabel("count")
    handles = [
        Line2D([], [], marker="o", ls="none", ms=4.5, color=C_SERIES_1,
               label=f"completed  (n = {len(ok)})"),
        Line2D([], [], marker="o", ls="none", ms=4.5, markerfacecolor="none",
               markeredgecolor=C_SERIES_2, markeredgewidth=0.9,
               label=f"failed / missing  (n = {len(bad)})"),
    ]
    fig.legend(handles=handles, loc="upper right", bbox_to_anchor=(0.99, 0.98), ncol=1)
    fig.tight_layout(pad=0.4)
    save_figure(fig, OUT / "fig_design_censoring.pdf")

    RESULTS["censoring_means"] = {
        key: {"completed": float(ok[key].mean()), "failed": float(bad[key].mean())}
        for key, _ in labels
    }

    # ------------------------------------------------------------------
    print("fig_failure_rate_ctop.pdf")

    def quartile_failure(column: str):
        edges = np.quantile(validity[column], [0.0, 0.25, 0.5, 0.75, 1.0])
        codes = np.clip(
            np.searchsorted(edges[1:-1], validity[column].to_numpy(float), side="right"), 0, 3
        )
        rate = np.array([float((~completed)[codes == k].mean()) for k in range(4)])
        count = np.array([int((codes == k).sum()) for k in range(4)])
        return rate, count, edges

    fig, axes = plt.subplots(1, 2, figsize=(FIG_WIDTH_IN, 2.9), sharey=True)
    for ax, (column, xlabel) in zip(
        axes,
        [("c_nom_top_mm", "$c_{nom,top}$ quartile [mm]"),
         ("Fcm_MPa", "$f_{cm}$ quartile [MPa]")],
    ):
        rate, count, edges = quartile_failure(column)
        xs = np.arange(4)
        ax.bar(xs, rate, width=0.62, color=C_SERIES_1, lw=0, zorder=2)
        for x, value in zip(xs, rate):
            ax.annotate(f"{value:.2f}", xy=(x, value), xytext=(0, 3),
                        textcoords="offset points", ha="center", va="bottom",
                        fontsize=9.0, color=C_INK_2, zorder=5,
                        bbox={"boxstyle": "square,pad=0.10", "facecolor": "white",
                              "edgecolor": "none"})
        ax.set_xticks(xs)
        ax.set_xticklabels(
            [f"Q{k + 1}\n{edges[k]:.0f} to {edges[k + 1]:.0f}" for k in range(4)]
        )
        ax.set_xlabel(xlabel)
        ax.set_ylim(0, 1.0)
        ax.grid(axis="x", visible=False)
        RESULTS[f"failure_rate_by_{column}"] = {
            f"Q{k + 1}": {"rate": float(rate[k]), "n": int(count[k]),
                          "range": [float(edges[k]), float(edges[k + 1])]}
            for k in range(4)
        }
    axes[0].set_ylabel("failure rate [-]")
    for ax in axes:
        ax.axhline(RESULTS["overall_failure_rate"], color=C_INK_2, lw=0.8,
                   ls=(0, (4, 2.5)), zorder=3)
    axes[0].legend(
        handles=[Line2D([], [], color=C_INK_2, lw=0.8, ls=(0, (4, 2.5)),
                        label=f"overall rate {RESULTS['overall_failure_rate']:.2f}"
                              f"  ({RESULTS['n_failed']}/{RESULTS['n_design']})")],
        loc="upper right",
    )
    fig.tight_layout(pad=0.4)
    save_figure(fig, OUT / "fig_failure_rate_ctop.pdf")

    # ------------------------------------------------------------------
    print("fig_completion_surface.pdf")
    fig = completion_surface(
        model,
        features(validity),
        completed,
        float(domain["completion_threshold"]),
    )
    save_figure(fig, OUT / "fig_completion_surface.pdf")
    RESULTS["completion_threshold"] = float(domain["completion_threshold"])
    RESULTS["completion_design_inside_fraction"] = float(domain["design_inside_fraction"])

    # ------------------------------------------------------------------
    print("fig_calibration.pdf")
    fig = calibration_plot(
        completion["calibration_table"],
        float(completion["cv_roc_auc"]),
        float(completion["cv_brier_score"]),
        float(completion["expected_calibration_error"]),
    )
    save_figure(fig, OUT / "fig_calibration.pdf")
    RESULTS["completion_auc"] = float(completion["cv_roc_auc"])
    RESULTS["completion_brier"] = float(completion["cv_brier_score"])
    RESULTS["completion_ece"] = float(completion["expected_calibration_error"])

    # ------------------------------------------------------------------
    print("fig_peak_stats.pdf")
    peak_kN = raw["P_max_N"].to_numpy(float) / 1000.0
    u_peak = raw["u_peak_mm"].to_numpy(float)
    fig, axes = plt.subplots(1, 2, figsize=(FIG_WIDTH_IN, 2.9))
    for ax, data, xlabel in [
        (axes[0], peak_kN, "Peak load $RF_{2,\\max}$ [kN]"),
        (axes[1], u_peak, "Displacement at peak $U_{2,peak}$ [mm]"),
    ]:
        counts, _, _ = ax.hist(data, bins=22, color=C_SERIES_1, alpha=0.85, lw=0, zorder=2)
        mean, std = float(np.mean(data)), float(np.std(data, ddof=1))
        ax.axvline(mean, color=C_SERIES_2, lw=1.4, zorder=3)
        ax.annotate(
            f"n = {len(data)}\nmean = {mean:.2f}\nstd = {std:.2f}\nCoV = {std / mean * 100:.1f}%",
            xy=(0.03, 0.97), xycoords="axes fraction", **ANNOT,
        )
        ax.set_xlabel(xlabel)
        ax.set_ylim(0, counts.max() * 1.42)
        ax.grid(axis="x", visible=False)
    axes[0].set_ylabel("count")
    axes[1].set_ylabel("count")
    axes[1].legend(handles=[Line2D([], [], color=C_SERIES_2, lw=1.4, label="mean")],
                   loc="upper right")
    fig.tight_layout(pad=0.4)
    save_figure(fig, OUT / "fig_peak_stats.pdf")

    for key, data in (("peak_load_kN", peak_kN), ("U2_at_peak_mm", u_peak)):
        RESULTS[key] = {
            "mean": float(np.mean(data)), "std": float(np.std(data, ddof=1)),
            "cov_pct": float(np.std(data, ddof=1) / np.mean(data) * 100),
            "min": float(data.min()), "max": float(data.max()),
            "median": float(np.median(data)),
            "p05_p95": [float(np.percentile(data, 5)), float(np.percentile(data, 95))],
        }

    # ------------------------------------------------------------------
    print("fig_peak_vs_inputs.pdf")
    fig, axes = plt.subplots(1, 3, figsize=(FIG_WIDTH_IN, 2.5), sharey=True)
    RESULTS["pearson_peak_vs_inputs"] = {}
    for ax, (column, xlabel) in zip(
        axes,
        [("Fcm_MPa", "$f_{cm}$ [MPa]"),
         ("c_nom_top_mm", "$c_{nom,top}$ [mm]"),
         ("c_nom_bottom_mm", "$c_{nom,bot}$ [mm]")],
    ):
        x = raw[column].to_numpy(float)
        r = pearson(x, peak_kN)
        RESULTS["pearson_peak_vs_inputs"][column] = r
        ax.scatter(x, peak_kN, s=9, color=C_SERIES_1, lw=0, alpha=0.7, zorder=2)
        ax.annotate(f"$r$ = {r:+.3f}", xy=(0.04, 0.96), xycoords="axes fraction", **ANNOT)
        ax.set_xlabel(xlabel)
    axes[0].set_ylabel("Peak load [kN]")
    fig.tight_layout(pad=0.4)
    save_figure(fig, OUT / "fig_peak_vs_inputs.pdf")

    # ------------------------------------------------------------------
    print("fig_E_collinearity.pdf")
    fcm = design["Fcm_MPa"].to_numpy(float)
    modulus = design["E_MPa"].to_numpy(float)
    xs = np.linspace(fcm.min(), fcm.max(), 400)
    residual = modulus - 22000.0 * (fcm / 10.0) ** 0.3
    fig, ax = plt.subplots(figsize=(FIG_WIDTH_IN, 3.2))
    ax.scatter(fcm, modulus, s=11, color=C_SERIES_1, lw=0, alpha=0.6, zorder=2,
               label=f"LHS design points (n = {len(design)})")
    ax.plot(xs, 22000.0 * (xs / 10.0) ** 0.3, color=C_SERIES_2, lw=1.6, zorder=3,
            label=r"EC2: $E = 22000\,(f_{cm}/10)^{0.3}$")
    ax.set_xlabel("$f_{cm}$ [MPa]")
    ax.set_ylabel("$E$ [MPa]")
    ax.annotate(
        "Spearman $\\rho$ = 1.0\n(deterministic dependence,\n"
        f"max residual = {np.max(np.abs(residual)):.1e} MPa)",
        xy=(0.04, 0.96), xycoords="axes fraction", **ANNOT,
    )
    ax.legend(loc="lower right")
    fig.tight_layout(pad=0.4)
    save_figure(fig, OUT / "fig_E_collinearity.pdf")

    RESULTS["E_fcm"] = {
        "spearman_rho": spearman(fcm, modulus),
        "pearson_r": pearson(fcm, modulus),
        "max_abs_residual_MPa": float(np.max(np.abs(residual))),
        "E_range_MPa": [float(modulus.min()), float(modulus.max())],
    }

    # ------------------------------------------------------------------
    print("fig_stiffness_vs_ctop.pdf")
    k0 = raw["k0_N_per_mm"].to_numpy(float) / 1000.0
    ctop = raw["c_nom_top_mm"].to_numpy(float)
    r_k0 = pearson(ctop, k0)
    fig, ax = plt.subplots(figsize=(FIG_WIDTH_IN, 3.2))
    ax.scatter(ctop, k0, s=11, color=C_SERIES_1, lw=0, alpha=0.7, zorder=2)
    ax.set_xlabel("$c_{nom,top}$ [mm]")
    ax.set_ylabel("Initial stiffness $k_0$ [kN/mm]")
    ax.annotate(f"$r$ = {r_k0:+.3f}   (n = {len(raw)})",
                xy=(0.04, 0.96), xycoords="axes fraction", **ANNOT)
    fig.tight_layout(pad=0.4)
    save_figure(fig, OUT / "fig_stiffness_vs_ctop.pdf")

    RESULTS["k0_kN_per_mm"] = {
        "pearson_r_vs_c_nom_top": r_k0,
        "pearson_r_vs_Fcm": pearson(raw["Fcm_MPa"], k0),
        "pearson_r_vs_c_nom_bottom": pearson(raw["c_nom_bottom_mm"], k0),
        "mean": float(np.mean(k0)), "std": float(np.std(k0, ddof=1)),
        "min": float(k0.min()), "max": float(k0.max()),
    }

    # ------------------------------------------------------------------
    # Phase P3: registration and reduction. The ablation's own numbers are written by
    # scripts/ablation_1_registration.py; what is read back here is only what the figures
    # draw, so no number is computed in two places.
    register_dir = _stage(REGISTER_STAGE, digest)
    reduce_dir = _stage(REDUCE_STAGE, digest)
    stations = np.linspace(0.0, 1.0, 201)

    _jobs, registered = curve_matrix(pd.read_parquet(register_dir / AMPLITUDE_PARQUET))
    _j2, unregistered = curve_matrix(
        pd.read_parquet(register_dir / AMPLITUDE_UNREGISTERED_PARQUET)
    )
    _j3, gamma = curve_matrix(pd.read_parquet(register_dir / WARP_PARQUET))
    bases = json.loads((reduce_dir / BASIS_JSON).read_text(encoding="utf-8"))
    amplitude_block = next(
        block for block in bases["blocks"] if block["name"] == "amplitude"
    )

    print("fig_registration_before_after.pdf")
    save_figure(
        registration_before_after(stations, unregistered, registered),
        OUT / "fig_registration_before_after.pdf",
    )
    RESULTS["registration"] = {
        "mean_pointwise_std_unregistered_N": float(unregistered.std(axis=0).mean()),
        "mean_pointwise_std_registered_N": float(registered.std(axis=0).mean()),
        "mean_peak_unregistered_kN": float(unregistered.max(axis=1).mean() / 1000.0),
        "mean_peak_registered_kN": float(registered.max(axis=1).mean() / 1000.0),
    }

    print("fig_warp_family.pdf")
    save_figure(warp_family(stations, gamma), OUT / "fig_warp_family.pdf")
    RESULTS["warp"] = {
        "n_warps": int(gamma.shape[0]),
        "max_abs_deviation_from_identity": float(np.abs(gamma - stations).max()),
    }

    print("fig_scree.pdf")
    # The unregistered basis is refitted here rather than read from an artifact because it
    # is the ablation's comparison case and never ships in the pipeline's own reduction.
    unregistered_curve_basis = fit_basis(rf2_grid * 1000.0, "unregistered", 0.99)
    save_figure(
        scree(
            np.array(amplitude_block["explained_variance_ratio"], dtype=float),
            unregistered_curve_basis.explained_variance_ratio,
            float(bases["variance_target"]),
            int(amplitude_block["n_retained"]),
            int(unregistered_curve_basis.n_retained),
        ),
        OUT / "fig_scree.pdf",
    )
    RESULTS["components_at_target"] = {
        "registered_amplitude": int(amplitude_block["n_retained"]),
        "unregistered_curves": int(unregistered_curve_basis.n_retained),
    }

    print("fig_amplitude_loadings.pdf")
    save_figure(
        amplitude_loadings(
            stations,
            np.array(amplitude_block["components"], dtype=float),
            np.array(amplitude_block["explained_variance_ratio"], dtype=float),
        ),
        OUT / "fig_amplitude_loadings.pdf",
    )

    # ------------------------------------------------------------------
    # Phase P4: the Gaussian process surrogate and the fold honest baseline comparison. The
    # scalar predictions are the validate stage's own leave one out output, read back rather
    # than recomputed, because a figure is not where a number gets a second, unaudited chance
    # to be measured.
    validate_dir = _stage(VALIDATE_STAGE, digest)
    baselines = json.loads((validate_dir / BASELINES_JSON).read_text(encoding="utf-8"))
    predictions_frame = pd.read_parquet(validate_dir / SCALAR_PREDICTIONS_PARQUET)
    scalar_lookup = {
        (str(row["target"]), str(row["model"])): row
        for row in baselines["scalar"]
        if row["harness"] == "leave_one_out"
    }

    print("fig_pmax_predicted_vs_actual.pdf")
    target = "P_max_N"
    target_rows = predictions_frame.loc[predictions_frame["target"] == target]
    truth_by_model = {
        model: group.sort_index()["truth"].to_numpy(dtype=float)
        for model, group in target_rows.groupby("model")
    }
    # Every model's rows describe the same 198 leave one out folds in the same job order, so
    # the truth column is identical across models; this is the assertion that it actually is.
    truths = next(iter(truth_by_model.values()))
    for other in truth_by_model.values():
        if not np.array_equal(other, truths):
            raise AssertionError(
                "the leave one out truth column differs between models for "
                f"{target!r}, so the scalar prediction table is not aligned by row."
            )
    predictions_by_model = {
        model: group.sort_index()["prediction"].to_numpy(dtype=float)
        for model, group in target_rows.groupby("model")
    }
    r2_by_model = {
        model: float(scalar_lookup[(target, model)]["r2_test"])
        for model in predictions_by_model
    }
    save_figure(
        predicted_vs_actual(
            truths, predictions_by_model, r2_by_model, 1.0 / 1000.0, "$P_{max}$ [kN]"
        ),
        OUT / "fig_pmax_predicted_vs_actual.pdf",
    )
    RESULTS["pmax_validation"] = {
        "r2_test": r2_by_model,
        "n_folds": int(baselines["context"]["n_folds"]),
    }

    RESULTS["config_sha256"] = digest
    (Path(__file__).resolve().parent / "figure_stats.json").write_text(
        json.dumps(RESULTS, indent=2, sort_keys=True) + "\n", encoding="utf-8", newline="\n"
    )
    print(f"\nAll figures written to {OUT}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
